### ISSUE TITLE
Equivalent functions

### ISSUE THREAD

**Issue by kennykarnama** [KLYgarage/football-klepto#4]
Implement functions for all available resources.
Refer to [this](https://www.football-data.org/documentation/quickstart) On **Available Resources** section

- [x] Competition
  - [x] List available
  - [x] Competition details
  - [x] Team playing on this competition
  - [x] Competition current standings
  - [x] Matches
- [x] Match
  - [x] Matches across multiple competition
  - [x] Single match detail
- [x] Single team details
- [x] Areas
  - [x] Available Area
  - [x] Area details

**Comment by charsme** [comment]
👍 Nice works Ken
